"""empty message

Revision ID: 95ad7a8ea26f
Revises: a5cffa318ac2
Create Date: 2026-03-21 16:17:03.971184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ad7a8ea26f'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('creature',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('droid',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('location',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('organization',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('specie',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('vehicle',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('favoritos',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('creature_id', sa.Integer(), nullable=True),
    sa.Column('droid_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('specie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character._id'], ),
    sa.ForeignKeyConstraint(['creature_id'], ['creature._id'], ),
    sa.ForeignKeyConstraint(['droid_id'], ['droid._id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location._id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization._id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['specie._id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    op.drop_table('favoritos')
    op.drop_table('vehicle')
    op.drop_table('specie')
    op.drop_table('organization')
    op.drop_table('location')
    op.drop_table('droid')
    op.drop_table('creature')
    op.drop_table('character')
    # ### end Alembic commands ###
