"""empty message

Revision ID: ad6e5dbc72a6
Revises: 586b0928d0bf
Create Date: 2026-03-24 16:44:59.339418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6e5dbc72a6'
down_revision = '586b0928d0bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PERSONAJE', 'VEHICULO', 'LUGAR', 'CRIATURA', 'DROIDE', 'ORGANIZACION', 'ESPECIE', name='tiporecurso'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favoritos_lugares')
    op.drop_table('favoritos_organizaciones')
    op.drop_table('favoritos_criaturas')
    op.drop_table('favoritos_especies')
    op.drop_table('favoritos_vehiculos')
    op.drop_table('favoritos_droides')
    op.drop_table('favoritos_personajes')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.create_table('favoritos_personajes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('personaje_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['personaje_id'], ['personaje.id'], name=op.f('favoritos_personajes_personaje_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favoritos_personajes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favoritos_personajes_pkey'))
    )
    op.create_table('favoritos_droides',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('droide_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['droide_id'], ['droide.id'], name=op.f('favoritos_droides_droide_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favoritos_droides_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favoritos_droides_pkey'))
    )
    op.create_table('favoritos_vehiculos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehiculo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favoritos_vehiculos_user_id_fkey')),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], name=op.f('favoritos_vehiculos_vehiculo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favoritos_vehiculos_pkey'))
    )
    op.create_table('favoritos_especies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('especie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['especie_id'], ['especie.id'], name=op.f('favoritos_especies_especie_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favoritos_especies_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favoritos_especies_pkey'))
    )
    op.create_table('favoritos_criaturas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('criatura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['criatura_id'], ['criatura.id'], name=op.f('favoritos_criaturas_criatura_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favoritos_criaturas_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favoritos_criaturas_pkey'))
    )
    op.create_table('favoritos_organizaciones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organizacion_id'], ['organizacion.id'], name=op.f('favoritos_organizaciones_organizacion_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favoritos_organizaciones_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favoritos_organizaciones_pkey'))
    )
    op.create_table('favoritos_lugares',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lugar_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugar.id'], name=op.f('favoritos_lugares_lugar_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('favoritos_lugares_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favoritos_lugares_pkey'))
    )
    op.drop_table('favorito')
    # ### end Alembic commands ###
